stages:
  clean_data:
    cmd: python clean_data.py
    deps:
    - clean_data.py
    - data.csv
    outs:
    - data_clean.csv
  estimate:
    cmd: python estimate.py
    deps:
    - data_clean.csv
    - estimate.py
    outs:
    - res.txt:
        cache: false
